"""
Markdown file generation for MyTake outputs.
"""

from pathlib import Path
from datetime import datetime
from typing import Dict
import re
from app.config import settings


class MarkdownGenerator:
    """Generate and save Markdown files for processed content."""

    @staticmethod
    def generate_filename(title: str, content_id: int) -> str:
        """Generate a safe filename from title."""
        # Remove special characters and replace spaces
        safe_title = re.sub(r'[^\w\s-]', '', title)
        safe_title = re.sub(r'[-\s]+', '-', safe_title)
        safe_title = safe_title[:50]  # Limit length

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"{timestamp}_{content_id}_{safe_title}.md"

    @staticmethod
    def generate_markdown(
        title: str,
        url: str,
        source_type: str,
        what_they_said_deep: str,
        what_they_said_simple: str,
        what_i_say_simple: str,
        what_i_say_deep: str,
        content_id: int = None,
        created_at = None
    ) -> str:
        """Generate markdown content."""

        if created_at is None:
            created_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        elif isinstance(created_at, str):
            # Parse ISO format string
            try:
                dt = datetime.fromisoformat(created_at.replace('Z', '+00:00'))
                created_str = dt.strftime("%Y-%m-%d %H:%M:%S")
            except:
                created_str = created_at[:19]  # Take first 19 chars (date and time)
        else:
            created_str = created_at.strftime("%Y-%m-%d %H:%M:%S")

        markdown = f"""# {title}

**Source**: {source_type.upper()}
**URL**: {url or "N/A"}
**Processed**: {created_str}
**MyTake ID**: {content_id or "N/A"}

---

## What they said — deep

{what_they_said_deep}

---

## What they said — simple

{what_they_said_simple}

---

## What I'd say — simple

{what_i_say_simple}

---

## What I'd say — deep

{what_i_say_deep}

---

*Generated by MyTake - A personal content digestion tool*
"""
        return markdown

    @staticmethod
    def save_markdown(markdown_content: str, filename: str) -> Path:
        """Save markdown content to file."""
        filepath = settings.docs_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        return filepath

    @staticmethod
    def create_and_save(content_data: Dict) -> str:
        """Create and save markdown file, return relative path."""
        filename = MarkdownGenerator.generate_filename(
            content_data.get("title", "Untitled"),
            content_data.get("id")
        )

        markdown_content = MarkdownGenerator.generate_markdown(
            title=content_data.get("title", "Untitled"),
            url=content_data.get("url"),
            source_type=content_data.get("source_type", "unknown"),
            what_they_said_deep=content_data.get("what_they_said_deep", ""),
            what_they_said_simple=content_data.get("what_they_said_simple", ""),
            what_i_say_simple=content_data.get("what_i_say_simple", ""),
            what_i_say_deep=content_data.get("what_i_say_deep", ""),
            content_id=content_data.get("id"),
            created_at=content_data.get("created_at")
        )

        filepath = MarkdownGenerator.save_markdown(markdown_content, filename)

        # Return relative path from data directory
        return f"docs/{filename}"
